printf("Enter your names below:");
printf("Russian pig");
printf("STEFFIN ABRAHAM");
printf("steny Rockzzz...");
printf("Sid.. :D");
printf("Shj_k");
printf("yoyohoneysing");
printf("vrinda white dog");
printf("sj_joy");
printf("romeo_bengaaali");
printf("ghostfreak0_0");
